### PR TITLE
Dataset page

### PR DESCRIPTION
**Pull request by luccasmmg**

### CODE REVIEW

**Comment by Gutts-n** [comment]
Different icons here: 
image
image
image
image

The buttons sizes differ from the mockup and the right button is misaligned with the one on the left.

image
image

No responsivity in the tabs sections generating horizontal scroll:
image

Copy to clipboard button bg color, icon, and spacing differ from the mockup:

image
image

The resources icons are a little flat compared with the mockup and the downloads icons differ from the mockup as well:
image
image
 
image
image

**Comment by luccasmmg** [comment]
> Different icons here: image image image image
> 
> The buttons sizes differ from the mockup and the right button is misaligned with the one on the left.
> 
> image image
> 
> No responsivity in the tabs sections generating horizontal scroll: image
> 
> Copy to clipboard button bg color, icon, and spacing differ from the mockup:
> 
> image image
> 
> The resources icons are a little flat compared with the mockup and the downloads icons differ from the mockup as well: image image
> 
> image image

The icon stuff im not really planning on fixing right now, i wanted to see if they had an icon pack first, cause loading the icons as svg images is not really nice since it requires extra http requests just to get the icon (Instead of having it in the mockup from the start) You can check that by using your browser to simulate a slow 3g and opening up the "Downloads" tab, the icons there were taken directly from the mockup, you will see them taking a while to load

The

- Lack of responsivness i will fix it 
- Missaligned buttons i will fix it
- The color in the copy to clipboard button as well

**Comment by luccasmmg** [comment]
The problem with taking the icons as images from the figma 

[Screencast from 2024-08-30 17-52-27.webm](https://github.com/user-attachments/assets/949eb4ff-e094-401e-9d79-a443d114efcb)

**Review by Gutts-n — CHANGES_REQUESTED** [review]
Different icons here: 
image
image
image
image

The buttons sizes differ from the mockup and the right button is misaligned with the one on the left.

image
image

No responsivity in the tabs sections generating horizontal scroll:
image

Copy to clipboard button bg color, icon, and spacing differ from the mockup:

image
image

The resources icons are a little flat compared with the mockup and the downloads icons differ from the mockup as well:
image
image
 
image
image

**Comment by Gutts-n** [comment]
LGTM.

**Pull request merged**
